class Helpers {
  static List<String> getLyrics() {
    return [
      "(Perreamos toda la noche y nos dormimo' a las die')",
      "",
      "Llegué al club con el combo, rápido la vi lejos",
      "Se pintaba los labios y la copa como espejo",
      "Se acercó, poco a poco, y yo queriendo que me baile",
      "Luego me dijo: Vamos, que te enseño Buenos Aire'",
      "",
      "Y nos fuimos en una, empezamo' a la una",
      "Y con la nota, rápido nos dieron las tres",
      "Perreamos toda la noche y nos dormimo' a las die'",
      "Ando rezándole a Dios pa' repetirlo otra ve'",
      "",
      "Y nos fuimos en una, empezamo' a la una",
      "Y con la nota, rápido nos dieron las tre'",
      "Perreamos toda la noche y nos dormimo' a las diez",
      "Ando rezándole a Dios pa' repetirlo otra ve'",
      "",
      "Dime, beba",
      "Fecha y hora y te paso a buscar",
      "Yo le llego donde los demás, tú sabes que, no le llegan",
      "Ruido de botellas de champán de las copas al brindar",
      "Pero solo escucho cómo late",
      "Mi corazón cuando veo ese cuerpo 'e escaparate",
      "El traje combina con la Mercede' Granate",
      "No hay otro, por más que ellos traten",
      "",
      "Quédate",
      "Que las noches, sin ti, duelen",
      "Tengo en la mente las pose' y todos los gemido'",
      "Que ya no quiero nada que no sea contigo",
      "",
      "Quédate",
      "Que las noches, sin ti, duelen",
      "Tengo en la mente las pose' y todo lo que hicimo'",
      "Que ya no quiero nada que no sea contigo",
      "",
      "Dale, guacha, suelta",
      "Vente pa' Canaria' sin el equipaje y sin viaje de vuelta",
      "Por la isla, te vo'a dar una vuelta",
      "",
      "Bebé, solo avisa",
      "El sábado teteo, el domingo misa",
      "Estoy a ver si me garantiza'",
      "Que te me pegas como quien graba con Biza",
      "",
      "Y vi salir a las amigas del party y ella se quedó",
      "Mirándonos a los ojo', no al reloj",
      "Y nos fuimos en Uber al apartamento",
      "En privado, me pedía que le diera un concierto",
      "Le dije que, por meno' de un beso, no canto",
      "",
      "Y nos fuimos en una, empezamo' a la una",
      "Y con la nota, rápido nos dieron las tre'",
      "Perreamos toda la noche y nos dormimo' a las die'",
      "Ando rezándole a Dios pa' repetirlo otra ve'",
      "",
      "Quédate",
      "Que las noches, sin ti, duelen",
      "Tengo en la mente las pose' y todos los gemido'",
      "Que ya no quiero nada que no sea contigo",
      "",
      "Quédate",
      "Que las noches, sin ti, duelen",
      "Tengo en la mente las pose' y todo lo que hicimo'",
      "Que ya no quiero nada que no sea contigo",
      "",
      "¡Bizarrap!",
      "Quevedo con el Biza, yeah-yeah-yeah",
      "LPGC, you know, oh-oh, oh-oh",
    ];
  }
}
